// <auto-generated />
namespace Wolfpack.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Events_renameGroup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Events_renameGroup));
        
        string IMigrationMetadata.Id
        {
            get { return "201805151121491_Events_renameGroup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
